development:
  adapter: postgresql
  encoding: unicode
  database: cat_development
  pool: 5
  username: cat
  password: 12345
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: cat_test
  pool: 5
  username: cat
  password: 12345
  host: localhost
